import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import { Flex, VStack, Heading  } from '@chakra-ui/react'

import StyleIt from '@/lib/SyleIt';


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>CryptoStamp</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
      </Head>

      <main>
        <StyleIt>
            <VStack 
              ml="auto"
              mr="auto"
              mt={5}
              p={5}
              color="green.400"
              backgroundColor="gray.700"
              maxW={800}
            >
              <VStack m={7}>
                <Heading m={1}>CryptoStamp</Heading>
                <Heading as="i" size="md" m={1}>Protect your writting on blockchain</Heading>
              </VStack>
              <Flex justify="center" mb={6}>
                <ConnectButton />
              </Flex>
            </VStack>
        </StyleIt>

      </main>

      <footer>
      </footer>
    </div>
  );
};

export default Home;
